name: "Terraform Infra Deployment"

on:
  push:
    branches: [ main ]

jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'   # very important for workload identity federation

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDS }}'

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initialize Terraform
        working-directory: ./terraform
        run: terraform init

      - name: Apply Terraform
        working-directory: ./terraform
        run: terraform apply -auto-approve

