name: "Terraform Infra Deployment"

on:
  push:
    branches: [ main ]

jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: ubuntu-latest

    env:
      GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDS }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          service_account_key: ${{ secrets.GOOGLE_CREDS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initialize Terraform
        working-directory: ./terraform
        run: terraform init

      - name: Apply Terraform
        working-directory: ./terraform
        run: terraform apply -auto-approve

